### ISSUE TITLE
error while compiling 1.3.2 version

### ISSUE THREAD

**Issue by VadikPrykhodko** [Emurgo/project-icarus-importer#12]
Following error has been received while compiling 1.3.2 version
Kindly advise 
builder for '/nix/store/rkm33dgw3qvv8xl720cq00ccqa2jxs5m-coreutils-8.29.drv' failed with exit code 2; last 10 log lines:
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/tmp/nix-build-coreutils-8.29.drv-0/coreutils-8.29'
Makefile:12204: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/tmp/nix-build-coreutils-8.29.drv-0/coreutils-8.29'
Makefile:11729: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-coreutils-8.29.drv-0/coreutils-8.29'
Makefile:12206: recipe for target 'check' failed
make: *** [check] Error 2
cannot build derivation '/nix/store/xy7aihsa3mribn01bdhfd6mzyzzyzkix-stdenv.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/217zsjkj76gipwj732ig5p173762vvxm-nixpkgs.drv': 1 dependencies couldn't be built
error: build of '/nix/store/217zsjkj76gipwj732ig5p173762vvxm-nixpkgs.drv' failed
(use '--show-trace' to show detailed location information)

**Comment by nicarq** [comment]
Hi @VadikPrykhodko we don’t have a current fork of cardano-sl, so the issues from 1.3.2 are not the same ones that you would get from this repo. Probably you should create an issue here https://github.com/input-output-hk/cardano-sl/issues
